### ISSUE TITLE
CBP - Reference Wallet - Crypto Broker - QA - Bug Wizard Customer Wallet

### ISSUE THREAD

**Issue by nelsonalfo** [Fermat-ORG/fermat#4753]
Pasos para reproducir el bug:
- Pasar por todos pasos del wizard para configurar la Customer Wallet
- Cerra la app fermat
- Abrir nuevamente la app y entrar en la Customer Wallet

En este punto aparece el wizarda de la wallet y cuando se intenta hacer de nuevo los pasos se produce un `NullPointerException`

```java
02-09 11:49:51.063 E/AndroidRuntime: FATAL EXCEPTION: main
                                     Process: com.bitdubai.fermat, PID: 7376
                                     java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.bitdubai.fermat_cbp_api.all_definition.identity.ActorIdentity.getPublicKey()' on a null object reference
                                         at com.bitdubai.fermat_cbp_plugin.layer.actor.crypto_customer.developer.bitdubai.version_1.database.CryptoCustomerActorDao.createNewCustomerIdentityWalletRelationship(CryptoCustomerActorDao.java:101)
                                         at com.bitdubai.fermat_cbp_plugin.layer.actor.crypto_customer.developer.bitdubai.version_1.structure.CustomerActorManager.createNewCustomerIdentityWalletRelationship(CustomerActorManager.java:46)
                                         at com.bitdubai.fermat_cbp_plugin.layer.wallet_module.crypto_customer.developer.bitdubai.version_1.structure.CryptoCustomerWalletModuleCryptoCustomerWalletManager.associateIdentity(CryptoCustomerWalletModuleCryptoCustomerWalletManager.java:412)
                                         at com.bitdubai.reference_wallet.crypto_customer_wallet.fragments.wizard_pages.WizardPageSetBitcoinWalletAndProvidersFragment.saveSettingAndGoNextStep(WizardPageSetBitcoinWalletAndProvidersFragment.java:310)
                                         at com.bitdubai.reference_wallet.crypto_customer_wallet.fragments.wizard_pages.WizardPageSetBitcoinWalletAndProvidersFragment.access$100(WizardPageSetBitcoinWalletAndProvidersFragment.java:57)
                                         at com.bitdubai.reference_wallet.crypto_customer_wallet.fragments.wizard_pages.WizardPageSetBitcoinWalletAndProvidersFragment$2.onClick(WizardPageSetBitcoinWalletAndProvidersFragment.java:182)
                                         at android.view.View.performClick(View.java:4756)
                                         at android.view.View$PerformClick.run(View.java:19749)
                                         at android.os.Handler.handleCallback(Handler.java:739)
                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                         at android.os.Looper.loop(Looper.java:135)
                                         at android.app.ActivityThread.main(ActivityThread.java:5221)
                                         at java.lang.reflect.Method.invoke(Native Method)
                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by franklinmarcano1970** [comment]
@Lozadaa @JDVilchez 
Por favor revisen este caso lo discutimos mas tarde, ahi se ve como duplicar el error, comienze a debugear.

**Comment by nelsonalfo** [comment]
El problema esta en el método del Module isWalletConfigured() Este no esta implementado, por lo que siempre se va a mostrar el  wizard, no importa si ya esta configurada la Wallet realmente. Como ya hay una identidad asociada a la Wallet no se muestra el diálogo y en consecuencia no se selecciona ninguna identidad. Cuando le das a next step se trata de obtener la info de la identidad, pero esto este es null por lo que lanza la excepción

**Comment by nelsonalfo** [comment]
El método isWalletConfigured evita que se mueste el wizard y se pase directamente al home de la Wallet

**Comment by franklinmarcano1970** [comment]
@Lozadaa Revisa este en metodo del module de la crypto customer broker com.bitdubai.fermat_cbp_plugin.layer.wallet_module.crypto_customer.developer.bitdubai.version_1.structure.CryptoCustomerWalletModuleCryptoCustomerWalletManager, busca el metodo isWalletConfigured, y implementa la logica que devuelva true si esta configurada la wallet, sino false, como sabemos eso, revisa esta clase, CryptoCustomerWalletPreferenceSettings, en la api del wallet module de la customer, ahi va a estar dos metodos getSelectedProviders y getSelectBitcoinWallet, debe de verifcar con el load del walletSetting, que esos metodos no esten vacios o nulos, si estan vacios uno de ellos entonces la wallet no esta configurada.
Hay una logica en la clase de android com/bitdubai/reference_wallet/crypto_customer_wallet/fragments/wizard_pages/WizardPageSetBitcoinWalletAndProvidersFragment.java,que maneja esa clase CryptoCustomerWalletPreferenceSettings, y puedes guiarte como hacer el load.
