### ISSUE TITLE
CBP - Reference Wallet - Crypto Broker - QA - Wallet Setting Exception

### ISSUE THREAD

**Issue by darkestpriest** [Fermat-ORG/fermat#4760]
Escenario:
Estaba probando una pantalla nueva en la broker wallet, la pantalla del detalle del contrato, hice todo el procedimiento de configuración inicial de la broker wallet, ingresé como Jhon Doe,cuando la pantalla que estaba haciendo, no funcionó correctamente. Detengo la app, vuelvo a entrar en la misma, ingreso a la broker wallet, teóricamente, los settings iniciales ya deberían estar guardados o fijados y debería saltarme esos pasos, pero, sale la pantalla de selección de la wallet de "earnings", la configuro y al darle next, la app se detiene y sale la siguiente excepción:
```java
02-09 14:34:40.108 2192-2192/com.bitdubai.fermat E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.bitdubai.fermat, PID: 2192
                                                                   java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.bitdubai.fermat_cbp_api.all_definition.identity.ActorIdentity.getPublicKey()' on a null object reference
                                                                       at com.bitdubai.fermat_cbp_plugin.layer.actor.crypto_broker.developer.bitdubai.version_1.database.CryptoBrokerActorDao.createNewBrokerIdentityWalletRelationship(CryptoBrokerActorDao.java:71)
                                                                       at com.bitdubai.fermat_cbp_plugin.layer.actor.crypto_broker.developer.bitdubai.version_1.structure.BrokerActorManager.createNewBrokerIdentityWalletRelationship(BrokerActorManager.java:56)
                                                                       at com.bitdubai.fermat_cbp_plugin.layer.wallet_module.crypto_broker.developer.bitdubai.version_1.structure.CryptoBrokerWalletModuleCryptoBrokerWalletManager.associateIdentity(CryptoBrokerWalletModuleCryptoBrokerWalletManager.java:441)
                                                                       at com.bitdubai.reference_wallet.crypto_broker_wallet.fragments.wizard_pages.WizardPageSetMerchandisesFragment.saveSettingAndGoNextStep(WizardPageSetMerchandisesFragment.java:347)
                                                                       at com.bitdubai.reference_wallet.crypto_broker_wallet.fragments.wizard_pages.WizardPageSetMerchandisesFragment.access$100(WizardPageSetMerchandisesFragment.java:51)
                                                                       at com.bitdubai.reference_wallet.crypto_broker_wallet.fragments.wizard_pages.WizardPageSetMerchandisesFragment$4.onClick(WizardPageSetMerchandisesFragment.java:174)
                                                                       at android.view.View.performClick(View.java:4780)
                                                                       at android.view.View$PerformClick.run(View.java:19866)
                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:135)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)```
Para que lo revises @nelsonalfo

**Comment by nelsonalfo** [comment]
Eso es porque cuando se verifica que esta configurada la Wallet se ejecuta un metodo que indica a android que debe pasar a otra pantalla la siguiente ves que se quiera entrar a esa Wallet. 

Ese método persiste dicha selección en un archivo XML para que la próxima vez que entres a la appa y quieras entrar a la Wallet, pases directamente al home. Ese método es de Matias y ya le informe la situación
