### ISSUE TITLE
CBP - Business Transaction - Customer Ack Offline Merchandise - QA - Null Pointer Exception when exists an incoming message

### ISSUE THREAD

**Issue by darkestpriest** [Fermat-ORG/fermat#4762]
Parent: #4069
When there is an incoming message from transaction Transmission network service, if the negotiation doesn't exists, the plugin throws the following exception:
```java
02-09 20:37:12.070 1934-2035/? E/AndroidRuntime: FATAL EXCEPTION: Thread-210
                                                 Process: com.bitdubai.fermat, PID: 1934
                                                 java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.bitdubai.fermat_cbp_api.layer.contract.customer_broker_sale.interfaces.CustomerBrokerContractSale.getContractId()' on a null object reference
                                                     at com.bitdubai.fermat_cbp_plugin.layer.business_transaction.customer_ack_offline_merchandise.developer.bitdubai.version_1.database.CustomerAckOfflineMerchandiseBusinessTransactionDao.buildDatabaseTableRecord(CustomerAckOfflineMerchandiseBusinessTransactionDao.java:697)
                                                     at com.bitdubai.fermat_cbp_plugin.layer.business_transaction.customer_ack_offline_merchandise.developer.bitdubai.version_1.database.CustomerAckOfflineMerchandiseBusinessTransactionDao.persistContractInDatabase(CustomerAckOfflineMerchandiseBusinessTransactionDao.java:676)
                                                     at com.bitdubai.fermat_cbp_plugin.layer.business_transaction.customer_ack_offline_merchandise.developer.bitdubai.version_1.structure.CustomerAckOfflineMerchandiseMonitorAgent$MonitorAgent.checkPendingEvent(CustomerAckOfflineMerchandiseMonitorAgent.java:369)
                                                     at com.bitdubai.fermat_cbp_plugin.layer.business_transaction.customer_ack_offline_merchandise.developer.bitdubai.version_1.structure.CustomerAckOfflineMerchandiseMonitorAgent$MonitorAgent.doTheMainTask(CustomerAckOfflineMerchandiseMonitorAgent.java:305)
                                                     at com.bitdubai.fermat_cbp_plugin.layer.business_transaction.customer_ack_offline_merchandise.developer.bitdubai.version_1.structure.CustomerAckOfflineMerchandiseMonitorAgent$MonitorAgent.run(CustomerAckOfflineMerchandiseMonitorAgent.java:199)
                                                     at java.lang.Thread.run(Thread.java:818)`

Please, check that in every business transaction

**Comment by darkestpriest** [comment]
Fixed
