### ISSUE TITLE
BCH- Crypto Network Bitcoin - Error trying to monitor the Bitcoin network

### ISSUE THREAD

**Issue by nattyco** [Fermat-ORG/fermat#5606]
Probando la Bitcoin Wallet cambiando a red testnet y pidiendo btc al faucet en el log veo estos errores.

03-29 17:15:00.526    4017-4101/org.fermat W/System.err﹕ org.bitcoinj.store.UnreadableWalletException: Could not parse input stream to protobuf
03-29 17:15:00.526    4017-4101/org.fermat W/System.err﹕ at org.bitcoinj.store.WalletProtobufSerializer.readWallet(WalletProtobufSerializer.java:402)
03-29 17:15:00.530    4017-4101/org.fermat W/System.err﹕ at org.bitcoinj.core.Wallet.loadFromFileStream(Wallet.java:1512)
03-29 17:15:00.530    4017-4101/org.fermat W/System.err﹕ at org.bitcoinj.core.Wallet.loadFromFile(Wallet.java:1450)
03-29 17:15:00.530    4017-4101/org.fermat W/System.err﹕ at com.bitdubai.fermat_bch_plugin.layer.crypto_network.bitcoin.developer.bitdubai.version_1.structure.BitcoinCryptoNetworkManager.getWallet(BitcoinCryptoNetworkManager.java:309)
03-29 17:15:00.530    4017-4101/org.fermat W/System.err﹕ at com.bitdubai.fermat_bch_plugin.layer.crypto_network.bitcoin.developer.bitdubai.version_1.structure.BitcoinCryptoNetworkManager.monitorNetworkFromKeyList(BitcoinCryptoNetworkManager.java:155)
03-29 17:15:00.534    4017-4101/org.fermat W/System.err﹕ at com.bitdubai.fermat_bch_plugin.layer.crypto_network.bitcoin.developer.bitdubai.version_1.BitcoinCryptoNetworkPluginRoot.monitorNetworkFromKeyList(BitcoinCryptoNetworkPluginRoot.java:157)
03-29 17:15:00.534    4017-4101/org.fermat W/System.err﹕ at com.bitdubai.fermat_bch_plugin.layer.crypto_vault.developer.bitdubai.version_1.structure.VaultKeyHierarchyMaintainer$VaultKeyHierarchyMaintainerAgent.doTheMainTask(VaultKeyHierarchyMaintainer.java:213)
03-29 17:15:00.534    4017-4101/org.fermat W/System.err﹕ at com.bitdubai.fermat_bch_plugin.layer.crypto_vault.developer.bitdubai.version_1.structure.VaultKeyHierarchyMaintainer$VaultKeyHierarchyMaintainerAgent.run(VaultKeyHierarchyMaintainer.java:123)
03-29 17:15:00.534    4017-4101/org.fermat W/System.err﹕ at java.lang.Thread.run(Thread.java:841)
03-29 17:15:00.534    4017-4101/org.fermat W/System.err﹕ Caused by: java.lang.IllegalStateException: Context does not match implicit network params: org.bitcoinj.params.RegTestParams@2b55c76b vs org.bitcoinj.params.TestNet3Params@14ccf24b
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ at org.bitcoinj.core.Context.getOrCreate(Context.java:102)
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ at org.bitcoinj.core.Wallet.<init>(Wallet.java:258)
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ at org.bitcoinj.store.WalletProtobufSerializer$1.create(WalletProtobufSerializer.java:97)
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ at org.bitcoinj.store.WalletProtobufSerializer.readWallet(WalletProtobufSerializer.java:435)
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ at org.bitcoinj.store.WalletProtobufSerializer.readWallet(WalletProtobufSerializer.java:398)
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ ... 8 more
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ ========================================================================================================================================================
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ Fermat Error Manager * Unexpected Exception Report
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ ========================================================================================================================================================
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ Source: BITDUBAI_BITCOIN_CRYPTO_NETWORK
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ Severity: DISABLES_SOME_FUNCTIONALITY_WITHIN_THIS_PLUGIN
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ ********************************************************************************************************************************************************
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ Exception Number: 1
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ Exception Type: class java.lang.NullPointerException
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ Exception Message: null
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ Exception Possible Cause: N/A
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ Exception Context:
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ N/A
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ Exception Stack Trace:
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ Class: com.bitdubai.fermat_bch_plugin.layer.crypto_network.bitcoin.developer.bitdubai.version_1.structure.BitcoinCryptoNetworkManager - Line: 156
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ Class: com.bitdubai.fermat_bch_plugin.layer.crypto_network.bitcoin.developer.bitdubai.version_1.BitcoinCryptoNetworkPluginRoot - Line: 157
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ Class: com.bitdubai.fermat_bch_plugin.layer.crypto_vault.developer.bitdubai.version_1.structure.VaultKeyHierarchyMaintainer$VaultKeyHierarchyMaintainerAgent - Line: 213
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ Class: com.bitdubai.fermat_bch_plugin.layer.crypto_vault.developer.bitdubai.version_1.structure.VaultKeyHierarchyMaintainer$VaultKeyHierarchyMaintainerAgent - Line: 123
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ Class: java.lang.Thread - Line: 841
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ Exceptions Processed: 1
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ ========================================================================================================================================================
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ Exception Number: 1
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ Exception Type: class com.bitdubai.fermat_bch_api.layer.crypto_network.bitcoin.exceptions.CantMonitorBitcoinNetworkException
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ Exception Message: There was an error trying to monitor the Bitcoin network
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ Exception Possible Cause: N/A
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ Exception Context:
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ N/A
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ Exception Stack Trace:
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ Class: com.bitdubai.fermat_bch_plugin.layer.crypto_network.bitcoin.developer.bitdubai.version_1.BitcoinCryptoNetworkPluginRoot - Line: 160
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ Class: com.bitdubai.fermat_bch_plugin.layer.crypto_vault.developer.bitdubai.version_1.structure.VaultKeyHierarchyMaintainer$VaultKeyHierarchyMaintainerAgent - Line: 213
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ Class: com.bitdubai.fermat_bch_plugin.layer.crypto_vault.developer.bitdubai.version_1.structure.VaultKeyHierarchyMaintainer$VaultKeyHierarchyMaintainerAgent - Line: 123
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ Class: java.lang.Thread - Line: 841
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ [ 03-29 17:15:00.538  4017: 4101 W/System.err ]
            at com.bitdubai.fermat_bch_plugin.layer.crypto_network.bitcoin.developer.bitdubai.version_1.BitcoinCryptoNetworkPluginRoot.monitorNetworkFromKeyList(BitcoinCryptoNetworkPluginRoot.java:160)
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ at com.bitdubai.fermat_bch_plugin.layer.crypto_vault.developer.bitdubai.version_1.structure.VaultKeyHierarchyMaintainer$VaultKeyHierarchyMaintainerAgent.doTheMainTask(VaultKeyHierarchyMaintainer.java:213)
03-29 17:15:00.538    4017-4101/org.fermat W/System.err﹕ at com.bitdubai.fermat_bch_plugin.layer.crypto_vault.developer.bitdubai.version_1.structure.VaultKeyHierarchyMaintainer$VaultKeyHierarchyMaintainerAgent.run(VaultKeyHierarchyMaintainer.java:123)
03-29 17:15:00.542    4017-4101/org.fermat W/System.err﹕ at java.lang.Thread.run(Thread.java:841)

**Comment by acostarodrigo** [comment]
Please, retry after upgrading from develop branch from yesterday and retry.

**Comment by nattyco** [comment]
@acostarodrigo  el error persiste, al cerrar y abrir la app de nuevo vuelve a dar este error, no he pedido btc ni hecho transacciones

03-31 15:40:38.845    4355-4435/org.fermat W/art﹕ Long monitor contention event with owner method=java.lang.String java.lang.Class.getNameNative!() from Class.java:4294967294 waiters=0 for 23.777s
03-31 15:40:38.847    4355-4434/org.fermat W/System.err﹕ ========================================================================================================================================================
03-31 15:40:38.847    4355-4434/org.fermat W/System.err﹕ Fermat Error Manager * Unexpected Exception Report
03-31 15:40:38.847    4355-4434/org.fermat W/System.err﹕ ========================================================================================================================================================
03-31 15:40:38.847    4355-4434/org.fermat W/System.err﹕ Source: BITDUBAI_BITCOIN_CRYPTO_NETWORK
03-31 15:40:38.847    4355-4434/org.fermat W/System.err﹕ Severity: DISABLES_SOME_FUNCTIONALITY_WITHIN_THIS_PLUGIN
03-31 15:40:38.847    4355-4434/org.fermat W/System.err﹕ ********************************************************************************************************************************************************
03-31 15:40:38.847    4355-4434/org.fermat W/System.err﹕ Exception Number: 1
03-31 15:40:38.847    4355-4434/org.fermat W/System.err﹕ Exception Type: class java.lang.NullPointerException
03-31 15:40:38.848    4355-4434/org.fermat W/System.err﹕ Exception Message: Attempt to invoke virtual method 'org.bitcoinj.core.Context org.bitcoinj.core.Wallet.getContext()' on a null object reference
03-31 15:40:38.848    4355-4434/org.fermat W/System.err﹕ Exception Possible Cause: N/A
03-31 15:40:38.848    4355-4434/org.fermat W/System.err﹕ Exception Context:
03-31 15:40:38.848    4355-4434/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
03-31 15:40:38.848    4355-4434/org.fermat W/System.err﹕ N/A
03-31 15:40:38.848    4355-4434/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
03-31 15:40:38.848    4355-4434/org.fermat W/System.err﹕ Exception Stack Trace:
03-31 15:40:38.848    4355-4434/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
03-31 15:40:38.848    4355-4434/org.fermat W/System.err﹕ Class: com.bitdubai.fermat_bch_plugin.layer.crypto_network.bitcoin.developer.bitdubai.version_1.structure.BitcoinCryptoNetworkManager - Line: 156
03-31 15:40:38.848    4355-4434/org.fermat W/System.err﹕ Class: com.bitdubai.fermat_bch_plugin.layer.crypto_network.bitcoin.developer.bitdubai.version_1.BitcoinCryptoNetworkPluginRoot - Line: 157
03-31 15:40:38.848    4355-4434/org.fermat W/System.err﹕ Class: com.bitdubai.fermat_bch_plugin.layer.crypto_vault.developer.bitdubai.version_1.structure.VaultKeyHierarchyMaintainer$VaultKeyHierarchyMaintainerAgent - Line: 213
03-31 15:40:38.848    4355-4434/org.fermat W/System.err﹕ Class: com.bitdubai.fermat_bch_plugin.layer.crypto_vault.developer.bitdubai.version_1.structure.VaultKeyHierarchyMaintainer$VaultKeyHierarchyMaintainerAgent - Line: 123
03-31 15:40:38.848    4355-4434/org.fermat W/System.err﹕ Class: java.lang.Thread - Line: 818
03-31 15:40:38.848    4355-4434/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
03-31 15:40:38.848    4355-4434/org.fermat W/System.err﹕ Exceptions Processed: 1
03-31 15:40:38.848    4355-4434/org.fermat W/System.err﹕ ========================================================================================================================================================
03-31 15:40:38.849    4355-4434/org.fermat W/System.err﹕ Exception Number: 1
03-31 15:40:38.850    4355-4434/org.fermat W/System.err﹕ Exception Type: class com.bitdubai.fermat_bch_api.layer.crypto_network.bitcoin.exceptions.CantMonitorBitcoinNetworkException
03-31 15:40:38.850    4355-4434/org.fermat W/System.err﹕ Exception Message: There was an error trying to monitor the Bitcoin network
03-31 15:40:38.850    4355-4434/org.fermat W/System.err﹕ Exception Possible Cause: N/A
03-31 15:40:38.850    4355-4434/org.fermat W/System.err﹕ Exception Context:
03-31 15:40:38.851    4355-4434/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
03-31 15:40:38.851    4355-4434/org.fermat W/System.err﹕ N/A
03-31 15:40:38.851    4355-4434/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
03-31 15:40:38.851    4355-4434/org.fermat W/System.err﹕ Exception Stack Trace:
03-31 15:40:38.851    4355-4434/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
03-31 15:40:38.851    4355-4434/org.fermat W/System.err﹕ Class: com.bitdubai.fermat_bch_plugin.layer.crypto_network.bitcoin.developer.bitdubai.version_1.BitcoinCryptoNetworkPluginRoot - Line: 160
03-31 15:40:38.851    4355-4434/org.fermat W/System.err﹕ Class: com.bitdubai.fermat_bch_plugin.layer.crypto_vault.developer.bitdubai.version_1.structure.VaultKeyHierarchyMaintainer$VaultKeyHierarchyMaintainerAgent - Line: 213
03-31 15:40:38.851    4355-4434/org.fermat W/System.err﹕ Class: com.bitdubai.fermat_bch_plugin.layer.crypto_vault.developer.bitdubai.version_1.structure.VaultKeyHierarchyMaintainer$VaultKeyHierarchyMaintainerAgent - Line: 123
03-31 15:40:38.851    4355-4434/org.fermat W/System.err﹕ Class: java.lang.Thread - Line: 818
03-31 15:40:38.851    4355-4434/org.fermat W/System.err﹕ ---------------------------------------------------------------------------------
03-31 15:40:38.851    4355-4434/org.fermat W/System.err﹕ [ 03-31 15:40:38.851  4355: 4434 W/System.err ]
            at com.bitdubai.fermat_bch_plugin.layer.crypto_network.bitcoin.developer.bitdubai.version_1.BitcoinCryptoNetworkPluginRoot.monitorNetworkFromKeyList(BitcoinCryptoNetworkPluginRoot.java:160)
03-31 15:40:38.851    4355-4434/org.fermat W/System.err﹕ at com.bitdubai.fermat_bch_plugin.layer.crypto_vault.developer.bitdubai.version_1.structure.VaultKeyHierarchyMaintainer$VaultKeyHierarchyMaintainerAgent.doTheMainTask(VaultKeyHierarchyMaintainer.java:213)
03-31 15:40:38.851    4355-4434/org.fermat W/System.err﹕ at com.bitdubai.fermat_bch_plugin.layer.crypto_vault.developer.bitdubai.version_1.structure.VaultKeyHierarchyMaintainer$VaultKeyHierarchyMaintainerAgent.run(VaultKeyHierarchyMaintainer.java:123)
03-31 15:40:38.851    4355-4434/org.fermat W/System.err﹕ at java.lang.Thread.run(Thread.java:818)
03-31 15:40:38.875    4355-4435/org.fermat I/System.out﹕ ***CryptoNetwork*** Monitor Request from AOB vault on rtest for 200 keys...

**Comment by acostarodrigo** [comment]
please, reinstall the app. The blockchain and CryptoNetwork components need to be re loaded with new data.

I have just received bitcoins from regTest and TestNet networks without any problem.,
