### ISSUE TITLE
ART - Sub app - Artist Coummnity - The sub app menu is not working properly

### ISSUE THREAD

**Issue by darkestpriest** [Fermat-ORG/fermat#6086]
The sub app is stopped when an user selects the side Menu and press the back button.
In logcat we can find this exception:
`
E/ConnectionNotificationsFragment: Attempt to invoke virtual method 'void android.support.v4.widget.SwipeRefreshLayout.setOnRefreshListener(android.support.v4.widget.SwipeRefreshLayout$OnRefreshListener)' on a null object reference
                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.widget.SwipeRefreshLayout.setOnRefreshListener(android.support.v4.widget.SwipeRefreshLayout$OnRefreshListener)' on a null object reference
                                                                        at com.bitdubai.sub_app_artist_community.fragments.ConnectionsListFragment.onCreateView(ConnectionsListFragment.java:85)
                                                                        at android.app.Fragment.performCreateView(Fragment.java:2053)
                                                                        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
                                                                        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                                        at android.app.BackStackRecord.run(BackStackRecord.java:834)
                                                                        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
                                                                        at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:483)
                                                                        at android.support.v13.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:167)
                                                                        at android.support.v4.view.ViewPager.populate(ViewPager.java:1106)
                                                                        at android.support.v4.view.ViewPager.populate(ViewPager.java:952)
                                                                        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1474)
                                                                        at android.view.View.measure(View.java:17547)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                                        at android.view.View.measure(View.java:17547)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                        at android.view.View.measure(View.java:17547)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                                        at android.view.View.measure(View.java:17547)
                                                                        at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:940)
                                                                        at android.view.View.measure(View.java:17547)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                                        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                                        at android.view.View.measure(View.java:17547)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                        at android.view.View.measure(View.java:17547)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                                        at android.view.View.measure(View.java:17547)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                        at android.view.View.measure(View.java:17547)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                                        at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2615)
                                                                        at android.view.View.measure(View.java:17547)
                                                                        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2015)
                                                                        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1173)
                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1379)
                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
`
Is required to fix this UI misbehaviour.

**Comment by darkestpriest** [comment]
Fixed
