### ISSUE TITLE
ART/TKY - Sub App - Artist/Fan Identity 

### ISSUE THREAD

**Issue by alexanderejm** [Fermat-ORG/fermat#6148]
Under the following circumstance:
1) Make a clean install of the fermat APK(uninstall any previous one)
2)Create an Art or TKY fan or Artist identity
3)exit the aplication(close fermat)
4)enter again and when pressing on the "GOT IT" it doen't pass to the fermat menu and the following error occurs:

![screenshot from 2016-05-05 18 35 01](https://cloud.githubusercontent.com/assets/16577032/15059933/2871bcc8-12f0-11e6-9015-4ffea842d114.png)

`05-05 19:03:54.077 3650-3650/org.fermat E/AppsManagerService: App instaled in device null: main_desktop
05-05 19:03:54.077 3650-3650/org.fermat W/System.err: java.lang.NullPointerException: Attempt to invoke interface method 'com.bitdubai.fermat_api.layer.all_definition.navigation_structure.Activity com.bitdubai.fermat_api.layer.all_definition.navigation_structure.interfaces.FermatStructure.getActivity(com.bitdubai.fermat_api.layer.all_definition.navigation_structure.enums.Activities)' on a null object reference
05-05 19:03:54.077 3650-3650/org.fermat W/System.err:     at com.bitdubai.android_core.app.FermatActivity.goHome(FermatActivity.java:1459)
05-05 19:03:54.077 3650-3650/org.fermat W/System.err:     at com.bitdubai.fermat_android_api.layer.definition.wallet.AbstractFermatFragment.home(AbstractFermatFragment.java:150)
05-05 19:03:54.077 3650-3650/org.fermat W/System.err:     at com.bitdubai.sub_app.wallet_manager.fragment.welcome_wizard.WelcomeWizardFragment.onClick(WelcomeWizardFragment.java:205)
05-05 19:03:54.077 3650-3650/org.fermat W/System.err:     at android.view.View.performClick(View.java:5198)
05-05 19:03:54.077 3650-3650/org.fermat W/System.err:     at android.view.View$PerformClick.run(View.java:21147)
05-05 19:03:54.077 3650-3650/org.fermat W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
05-05 19:03:54.077 3650-3650/org.fermat W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
05-05 19:03:54.077 3650-3650/org.fermat W/System.err:     at android.os.Looper.loop(Looper.java:148)
05-05 19:03:54.077 3650-3650/org.fermat W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
05-05 19:03:54.077 3650-3650/org.fermat W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
05-05 19:03:54.077 3650-3650/org.fermat W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
05-05 19:03:54.077 3650-3650/org.fermat W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by darkestpriest** [comment]
@franklinmarcano1970 do you seen this bug in your repository?
