### ISSUE TITLE
ART -Sub App - Artist Community - Identity Selection exception

### ISSUE THREAD

**Issue by darkestpriest** [Fermat-ORG/fermat#6212]
If you don't have an Artist Identity created and enter to the Artist Community, you going to see this exception:
```shell
========================================================================================================================================================
05-19 12:01:04.073 8549-8549/org.fermat W/System.err: Fermat Error Manager * Unexpected Exception Report
05-19 12:01:04.073 8549-8549/org.fermat W/System.err: ========================================================================================================================================================
05-19 12:01:04.073 8549-8549/org.fermat W/System.err: Source: ACTIVITY
05-19 12:01:04.073 8549-8549/org.fermat W/System.err: Severity: CRASH
05-19 12:01:04.073 8549-8549/org.fermat W/System.err: ********************************************************************************************************************************************************
05-19 12:01:04.073 8549-8549/org.fermat W/System.err: Exception Number: 1
05-19 12:01:04.073 8549-8549/org.fermat W/System.err: Exception Type: class com.bitdubai.fermat_api.layer.modules.exceptions.ActorIdentityNotSelectedException
05-19 12:01:04.073 8549-8549/org.fermat W/System.err: Exception Message: 
05-19 12:01:04.073 8549-8549/org.fermat W/System.err: Exception Possible Cause: N/A
05-19 12:01:04.073 8549-8549/org.fermat W/System.err: Exception Context: 
05-19 12:01:04.073 8549-8549/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-19 12:01:04.073 8549-8549/org.fermat W/System.err: N/A
05-19 12:01:04.073 8549-8549/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-19 12:01:04.073 8549-8549/org.fermat W/System.err: Exception Stack Trace: 
05-19 12:01:04.073 8549-8549/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-19 12:01:04.073 8549-8549/org.fermat W/System.err: Class: com.bitdubai.fermat_art_plugin.layer.sub_app_module.artist_community.developer.bitdubai.version_1.structure.ArtistCommunityManager - Line: 672
05-19 12:01:04.073 8549-8549/org.fermat W/System.err: Class: java.lang.reflect.Method - Line: -2
05-19 12:01:04.073 8549-8549/org.fermat W/System.err: Class: java.lang.reflect.Method - Line: 372
05-19 12:01:04.073 8549-8549/org.fermat W/System.err: Class: com.bitdubai.android_core.app.common.version_1.communication.server_system_broker.aidl.CommunicationServerService$2 - Line: 608
05-19 12:01:04.073 8549-8549/org.fermat W/System.err: Class: java.util.concurrent.FutureTask - Line: 237
05-19 12:01:04.073 8549-8549/org.fermat W/System.err: Class: java.util.concurrent.ThreadPoolExecutor - Line: 1112
05-19 12:01:04.073 8549-8549/org.fermat W/System.err: Class: java.util.concurrent.ThreadPoolExecutor$Worker - Line: 587
05-19 12:01:04.073 8549-8549/org.fermat W/System.err: Class: java.lang.Thread - Line: 818
05-19 12:01:04.073 8549-8549/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-19 12:01:04.073 8549-8549/org.fermat W/System.err: Exceptions Processed: 1
05-19 12:01:04.073 8549-8549/org.fermat W/System.err: ========================================================================================================================================================
05-19 12:01:04.076 8549-8549/org.fermat I/ClientBrokerServiceAIDL: SendMessage return from server
05-19 12:01:04.088 8549-10714/org.fermat I/ClientBrokerServiceAIDL: SendMessage return from server
05-19 12:01:04.118 8549-14972/org.fermat I/ClientBrokerServiceAIDL: SendMessage return from server
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: Exception Number: 1
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: Exception Type: class com.bitdubai.fermat_api.layer.modules.exceptions.ActorIdentityNotSelectedException
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: Exception Message: 
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: Exception Possible Cause: N/A
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: Exception Context: 
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: N/A
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: Exception Stack Trace: 
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: Class: com.bitdubai.fermat_art_plugin.layer.sub_app_module.artist_community.developer.bitdubai.version_1.structure.ArtistCommunityManager - Line: 672
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: Class: java.lang.reflect.Method - Line: -2
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: Class: java.lang.reflect.Method - Line: 372
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: Class: com.bitdubai.android_core.app.common.version_1.communication.server_system_broker.aidl.CommunicationServerService$2 - Line: 608
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: Class: java.util.concurrent.FutureTask - Line: 237
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: Class: java.util.concurrent.ThreadPoolExecutor - Line: 1112
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: Class: java.util.concurrent.ThreadPoolExecutor$Worker - Line: 587
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: Class: java.lang.Thread - Line: 818
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-19 12:01:04.118 8549-14972/org.fermat W/System.err:     at com.bitdubai.fermat_art_plugin.layer.sub_app_module.artist_community.developer.bitdubai.version_1.structure.ArtistCommunityManager.getSelectedActorIdentity(ArtistCommunityManager.java:672)
05-19 12:01:04.118 8549-14972/org.fermat W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
05-19 12:01:04.118 8549-14972/org.fermat W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
05-19 12:01:04.118 8549-14972/org.fermat W/System.err:     at com.bitdubai.android_core.app.common.version_1.communication.server_system_broker.aidl.CommunicationServerService$2.call(CommunicationServerService.java:608)
05-19 12:01:04.118 8549-14972/org.fermat W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-19 12:01:04.118 8549-14972/org.fermat W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
05-19 12:01:04.118 8549-14972/org.fermat W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
05-19 12:01:04.118 8549-14972/org.fermat W/System.err:     at java.lang.Thread.run(Thread.java:818)
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: ========================================================================================================================================================
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: Fermat Error Manager * Unexpected Exception Report
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: ========================================================================================================================================================
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: Source: ACTIVITY
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: Severity: CRASH
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: ********************************************************************************************************************************************************
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: Exception Number: 1
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: Exception Type: class com.bitdubai.fermat_api.layer.modules.exceptions.ActorIdentityNotSelectedException
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: Exception Message: 
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: Exception Possible Cause: N/A
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: Exception Context: 
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: N/A
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: Exception Stack Trace: 
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: Class: com.bitdubai.fermat_art_plugin.layer.sub_app_module.artist_community.developer.bitdubai.version_1.structure.ArtistCommunityManager - Line: 672
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: Class: java.lang.reflect.Method - Line: -2
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: Class: java.lang.reflect.Method - Line: 372
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: Class: com.bitdubai.android_core.app.common.version_1.communication.server_system_broker.aidl.CommunicationServerService$2 - Line: 608
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: Class: java.util.concurrent.FutureTask - Line: 237
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: Class: java.util.concurrent.ThreadPoolExecutor - Line: 1112
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: Class: java.util.concurrent.ThreadPoolExecutor$Worker - Line: 587
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: Class: java.lang.Thread - Line: 818
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: Exceptions Processed: 1
05-19 12:01:04.118 8549-14972/org.fermat W/System.err: ===============================================================================================================================================
```

When you got out and enter in the artist community the selection dialog is showing correctly and we don't get this exception anymore, only showing in the first run.

**Comment by darkestpriest** [comment]
Fixed
