### ISSUE TITLE
ART -Sub App - Fan Community - Exception when we select the selection identities element in menu

### ISSUE THREAD

**Issue by darkestpriest** [Fermat-ORG/fermat#6213]
When you press the *"your identities"* Menu element we got this exception:
```Shell
Exception Type: class com.bitdubai.fermat_api.layer.all_definition.exceptions.InvalidParameterException
05-19 15:55:53.394 12438-12438/org.fermat W/System.err: Exception Message: INVALID PARAMETER
05-19 15:55:53.394 12438-12438/org.fermat W/System.err: Exception Possible Cause: This code is not valid for the Activities enum
05-19 15:55:53.394 12438-12438/org.fermat W/System.err: Exception Context: 
05-19 15:55:53.394 12438-12438/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-19 15:55:53.394 12438-12438/org.fermat W/System.err: Code Received: ASAFCLIL
05-19 15:55:53.394 12438-12438/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-19 15:55:53.394 12438-12438/org.fermat W/System.err: Exception Stack Trace: 
05-19 15:55:53.394 12438-12438/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-19 15:55:53.394 12438-12438/org.fermat W/System.err: Class: com.bitdubai.fermat_api.layer.all_definition.navigation_structure.enums.Activities - Line: 962
05-19 15:55:53.394 12438-12438/org.fermat W/System.err: Class: com.bitdubai.android_core.app.AppActivity - Line: 328
05-19 15:55:53.394 12438-12438/org.fermat W/System.err: Class: com.bitdubai.android_core.app.AppActivity - Line: 479
05-19 15:55:53.394 12438-12438/org.fermat W/System.err: Class: com.bitdubai.android_core.app.FermatActivity$11 - Line: 1676
05-19 15:55:53.394 12438-12438/org.fermat W/System.err: Class: android.os.Handler - Line: 739
05-19 15:55:53.394 12438-12438/org.fermat W/System.err: Class: android.os.Handler - Line: 95
05-19 15:55:53.394 12438-12438/org.fermat W/System.err: Class: android.os.Looper - Line: 135
05-19 15:55:53.394 12438-12438/org.fermat W/System.err: Class: android.app.ActivityThread - Line: 5254
05-19 15:55:53.394 12438-12438/org.fermat W/System.err: Class: java.lang.reflect.Method - Line: -2
05-19 15:55:53.394 12438-12438/org.fermat W/System.err: Class: java.lang.reflect.Method - Line: 372
05-19 15:55:53.394 12438-12438/org.fermat W/System.err: Class: com.android.internal.os.ZygoteInit$MethodAndArgsCaller - Line: 903
05-19 15:55:53.394 12438-12438/org.fermat W/System.err: Class: com.android.internal.os.ZygoteInit - Line: 698
05-19 15:55:53.394 12438-12438/org.fermat W/System.err: ---------------------------------------------------------------------------------
05-19 15:55:53.394 12438-12438/org.fermat W/System.err:     at com.bitdubai.fermat_api.layer.all_definition.navigation_structure.enums.Activities.getValueFromString(Activities.java:962)
05-19 15:55:53.394 12438-12438/org.fermat W/System.err:     at com.bitdubai.android_core.app.AppActivity.changeActivity(AppActivity.java:328)
05-19 15:55:53.394 12438-12438/org.fermat W/System.err:     at com.bitdubai.android_core.app.AppActivity.onNavigationMenuItemTouchListener(AppActivity.java:479)
05-19 15:55:53.394 12438-12438/org.fermat W/System.err:     at com.bitdubai.android_core.app.FermatActivity$11.run(FermatActivity.java:1676)
05-19 15:55:53.394 12438-12438/org.fermat W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
05-19 15:55:53.394 12438-12438/org.fermat W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
05-19 15:55:53.394 12438-12438/org.fermat W/System.err:     at android.os.Looper.loop(Looper.java:135)
05-19 15:55:53.394 12438-12438/org.fermat W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5254)
05-19 15:55:53.394 12438-12438/org.fermat W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
05-19 15:55:53.394 12438-12438/org.fermat W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
05-19 15:55:53.394 12438-12438/org.fermat W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
05-19 15:55:53.394 12438-12438/org.fermat W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
05-19 15:55:53.397 12438-12438/org.fermat E/AppActivity: nextActivity null, activity code: ASAFCLILfermat structure: public_key_art_fan_community```

Please @GaboHub check this

**Comment by GaboHub** [comment]
this is fixed in this commit: 
https://github.com/darkestpriest/fermat/commit/5eddd8eef3286fc44c38a24543b6d60b390bce2d
